name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/build.yml"
      - "ClassDumper/**"
      - "ClassDumper.xcodeproj/**"

jobs:
  build:
    name: Build
    runs-on: macos-14.2
    strategy:
      matrix:
        platform:
          - macOS
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: Build and Test
        uses: mxcl/xcodebuild@v1
        with:
          xcode: 15.2
          scheme: "ClassDumper"
          platform: ${{ matrix.platform }}
